(** This file is intended to be used as [Require] by every file
    generated by CFMLC. *)

Set Implicit Arguments.
Require Import LibTactics.
Require CFPrint.


(** Registration of CF axioms for use by [xwp] tactic.
    CFMLC generates lines of the form
[[
    Hint Extern 1 (RegisterCF myfunc) => CFHeader_Provide myfunc__cf.
]]

   Then the [xwp] tactic can call [ltac_database_get database_cf myfunc]
   to retrieve [myfunc__cf] as hypothesis as head of the goal. *)

Definition database_cf := True.

Notation "'RegisterCF' T" := (ltac_database (boxer CFPrint.database_cf) (boxer T) _)
  (at level 69, T at level 0) : cfheader_scope.

Ltac CFHeader_Provide T := Provide T.

