# The _CoqProject file is generated.

COQINCLUDE := "-Q . CFML"

COQWARNINGS := "-w -notation-overridden,-implicit-core-hint-db,-omega-is-deprecated,-ambiguous-paths,-irrelevant-format-only-parsing,-deprecated-hint-without-locality,-deprecated-ident-entry,-custom-entry-overridden"

include ../make/Makefile.generic
include ../make/Makefile.coqproject
