
SRC_FORCE := TLCbuffer Fmap SepFunctor LambdaSemantics LambdaCFTactics LambdaSep LambdaCF LambdaStruct LambdaSepRO SepMosel LambdaSepMosel LambdaSepROMosel ExampleROMosel ExampleListNonlifted ExampleListMosel

-include Makefile.main