CFML := $(shell cfmlc -where)
COQINCLUDE := "-R . Sek"
COQWARNINGS := "-w -notation-overridden,-implicit-core-hint-db,-omega-is-deprecated,-ambiguous-paths,-irrelevant-format-only-parsing,-deprecated-hint-without-locality,-deprecated-ident-entry,-custom-entry-overridden"
include $(CFML)/Makefile.enduser
